# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20160922_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_expirydate',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_mfgdate',
            new_name='manufacturing_date',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_id',
            new_name='s_no',
        ),
    ]
