# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20160927_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='serial_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='stocks',
            name='s_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Medicine'),
        ),
    ]
