# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_auto_20160927_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='s_name',
            new_name='name',
        ),
    ]
