# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20160928_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='stock_units',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='stocks',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='serial_no',
            field=models.AutoField(max_length=100000, primary_key=True),
        ),
    ]
