# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_auto_20160928_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100000, primary_key=True),
        ),
    ]
