# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.PositiveIntegerField(max_length=100000, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100000)),
                ('city', models.CharField(max_length=100000)),
                ('email_id', models.CharField(max_length=10000)),
            ],
        ),
    ]
