# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20160922_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
