# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email_id',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.PositiveIntegerField(max_length=1000000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
