# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_auto_20160925_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(default='Enter a website name'),
        ),
    ]
