# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_auto_20160925_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(),
        ),
    ]
