# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_auto_20160925_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(choices=[('VSB', 'Varanasi'), ('DEL', 'New Delhi'), ('BOM', 'Mumbai'), ('MAA', 'Chennai'), ('VSKP', 'Vishakapatanam'), ('RDP', 'Durgapur'), ('CCU', 'Kolkata'), ('SHM', 'Shimla')], max_length=1000000),
        ),
    ]
