# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_auto_20160925_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
