# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_auto_20160926_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.PositiveIntegerField(help_text='Enter the supplier ID', primary_key=True, serialize=False),
        ),
    ]
