# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_auto_20160926_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='email_id',
            new_name='email_ID',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_id',
            new_name='supplier_ID',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_name',
            new_name='supplier_Name',
        ),
    ]
