# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0012_auto_20160929_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(default='None', max_length=12),
        ),
    ]
