# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.PositiveIntegerField(max_length=100000, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=100000)),
                ('medicine_expirydate', models.DateField()),
                ('medicine_mfgdate', models.DateField()),
            ],
        ),
    ]
