# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stocks', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_expirydate',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_mfgdate',
            new_name='manufacturing_date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='medicine',
            name='name',
            field=models.CharField(default='Some', max_length=100000, primary_key=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='serial_no',
            field=models.AutoField(default=5, max_length=100000, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='something',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Medicine'),
        ),
    ]
