# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_auto_20160929_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='serial_no',
            field=models.AutoField(max_length=100000, primary_key=True),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
